services:
  app:
    build:
      context: .
      target: build
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.0.33"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
